### ISSUE TITLE
Unknown: Failed opening required 'system/router.php'

### ISSUE THREAD

**Issue by maliyshock** [hibbitts-design/grav-skeleton-course-hub#3]
I downloaded the archive.
Unpacked it.
Then I run php -S localhost:8004 system/router.php
And got this error.

Also, there is no system folder in the archive, and also the structure of the project is different from grav core.
Am I doing something wrong?

**Comment by maliyshock** [comment]
Documentation says to unpack the archive in the root folder and run webserver. But it does not work like that.
Also, the structure of inner folders looks like user folder structure. It seemed to me it should be there. I tried to do that as well, but it throws error there is no theme called "mytheme". Also, this skeleton does not provide any theme files. How it should work then?

**Comment by paulhibbitts** [comment]
Hi @maliyshock , did you download one of the release ZIP files? https://github.com/hibbitts-design/grav-skeleton-course-hub/releases

**Comment by maliyshock** [comment]
No, I downloaded the archive from there https://github.com/hibbitts-design/grav-skeleton-course-hub
That's it.

**Comment by paulhibbitts** [comment]
Glad it is working now!

**Comment by maliyshock** [comment]
Not so fast! =) I did not try it yet.
Also, could you say, where should I unzip the archive? In the root folder of the grav-core project? In the user folder? Is there possibility to install this by grav package manager?

**Comment by paulhibbitts** [comment]
🙂No worries, let's make sure you can get things going.

You should unzip the archive in the Web directory you want the skeleton to be available in. A Grav skeleton contains a complete Grav install.

Themes are installable by the grav package manager, but not ready-to-run skeletons.

If you have not seen this yet, here is an install video that might help: https://learn.hibbittsdesign.org/opencoursehub/install-configure-video

Let me know how it goes!

**Comment by maliyshock** [comment]
@paulhibbitts Thank you. Finally, it works!
I think you should update readme file maybe. It was unclear for me that I should go to releases tab and download something from there.

Thank you for help!

**Comment by maliyshock** [comment]
One more question. I need this skeleton to see how the layout of the website is built.
Right now the active theme is mytheme. But it does not have any templates.
Where should I look at to see the templates?

**Comment by maliyshock** [comment]
One more question. I need this skeleton to see how the layout of the website is built.
Right now the active theme is mytheme. But it does not have any templates.
Where should I look at to see the templates?
Does it take them from bootstrap4-open-matter? Why?

**Comment by paulhibbitts** [comment]
Hi @maliyshock , glad you got it going! The ReadMe currently contains direct links to ZIP releases so I am not sure I would add more info to go to the releases tab as well.

This skeleton is using a custom inherited theme called "Bootstrap4 Open Matter" (using Bootstrap4 as its parent theme) for all the heavy lifting. In addition, if you want to make custom theme changes that are not overwritten in future Bootstrap4 Open Matter updates the usual "MyTheme" inherited theme has also been provided as a place to do that. I created an inherited theme so any big changes that might happen to Bootstrap4 theme would be carried through.

You can learn more about how inherited themes work at: https://learn.getgrav.org/15/themes/customization#theme-inheritance

**Comment by paulhibbitts** [comment]
Hope the above answered your question, I will close the issue now.
