### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by ledoare** [hibbitts-design/grav-skeleton-course-hub#5]
I try from a week to download http://hibbittsdesign.org/blog/downloads/grav-skeleton-open-matter-multicourse-hub-site.zip
with no success : beaked archive ?

**Comment by paulhibbitts** [comment]
Hi @ledoare, could you please try this link and let me know if it works for you?
https://hibbittsdesign.org/blog/downloads/grav-skeleton-open-matter-multicourse-hub-site.zip

**Comment by ledoare** [comment]
From France, Brittany : It finally works this morning after few fails, usually the download stops before 60 MB but there It finally loads 69 MB.. I would like to take this opportunity to thank you for all this job,  I hope it will help students very much.. 🥇
